set -g mouse on

setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# enable activity alerts
setw -g monitor-activity on
set -g visual-activity on

#unbind C-b	# unbind default leader key
#set -g prefix C-a
